Numerai releases 2 datasets to the user:  numerai_training_data.csv and numerai_tournament_data.csv

These .csvs are too large to post. As a workaround, this script enables others to see *samples* of both datasets.

**Note: The training data is used to create, produce, and validate my model. Following validation, the model is run on the tournament data. Details in ___.ipynb**

In [32]:
##training data
#import libraries
import pandas as pd
import numpy as np

# read data
train = pd.read_csv("./numerai_training_data.csv")
print('TRAINING DATA')
print('Dimensions:')
print(train.shape)
print('Number of rows:')
print(train.shape[0])
print('Number of columns:')
print(train.shape[1])
print('First five rows of training data:')
train.head()

TRAINING DATA
Dimensions:
(535713, 54)
Number of rows:
535713
Number of columns:
54
First five rows of training data:

,id,era,data_type,feature1,feature2,feature3,feature4,feature5,feature6,feature7,...,feature42,feature43,feature44,feature45,feature46,feature47,feature48,feature49,feature50,target
0,nb5059fbc40534a1,era1,train,0.49282,0.58077,0.48948,0.56762,0.56107,0.51168,0.47459,...,0.40333,0.52337,0.60795,0.35748,0.49677,0.28295,0.65342,0.57915,0.51136,1
1,nb2bb43f474f2429,era1,train,0.53427,0.72712,0.61895,0.66238,0.47163,0.66996,0.37673,...,0.46847,0.44557,0.64831,0.28245,0.68554,0.26547,0.59322,0.53156,0.61621,0
2,n1e960207daad44a,era1,train,0.54888,0.46304,0.49582,0.52395,0.57362,0.46969,0.50229,...,0.74065,0.41003,0.43230,0.78286,0.52214,0.43961,0.46139,0.61272,0.72566,1
3,n5e99b4326e6f463,era1,train,0.64488,0.56167,0.72591,0.52219,0.49311,0.51511,0.45514,...,0.67751,0.43340,0.67009,0.50086,0.51208,0.58674,0.54358,0.58602,0.51818,0
4,nf454131816e5401,era1,train,0.45235,0.56569,0.54424,0.34145,0.67652,0.44318,0.45627,...,0.40709,0.58624,0.44531,0.66276,0.41992,0.58741,0.62276,0.31212,0.22357,0

In [33]:
##tournament data
# read data
tour = pd.read_csv("./numerai_tournament_data.csv")
print('TOURNAMENT DATA')
print('Dimensions:')
print(tour.shape)
print('Number of rows:')
print(tour.shape[0])
print('Number of columns:')
print(tour.shape[1])
print('First five rows of tournament data:')
tour.head()

TOURNAMENT DATA
Dimensions:
(348831, 54)
Number of rows:
348831
Number of columns:
54
First five rows of tournament data:

,id,era,data_type,feature1,feature2,feature3,feature4,feature5,feature6,feature7,...,feature42,feature43,feature44,feature45,feature46,feature47,feature48,feature49,feature50,target
0,n614950e52f86476,era86,validation,0.73321,0.40769,0.52738,0.62752,0.53157,0.39902,0.60185,...,0.73091,0.46047,0.70016,0.46789,0.37077,0.60445,0.30939,0.65382,0.60536,0.0
1,n8c131af804784b6,era86,validation,0.41095,0.49730,0.57336,0.34116,0.60004,0.65085,0.41450,...,0.61655,0.54469,0.54147,0.47559,0.35006,0.58956,0.46743,0.39537,0.35831,1.0
2,n68cdeacc1d654de,era86,validation,0.53106,0.52798,0.40962,0.74406,0.42711,0.65237,0.49803,...,0.65628,0.45790,0.75984,0.54364,0.53942,0.50660,0.53929,0.66115,0.81356,0.0
3,n59b64bb3be044f0,era86,validation,0.37164,0.34754,0.57658,0.39391,0.53413,0.40982,0.49490,...,0.48189,0.49643,0.38714,0.70947,0.35190,0.75937,0.46353,0.40733,0.47283,0.0
4,nb859519b853849e,era86,validation,0.57009,0.47230,0.55039,0.59870,0.40695,0.41777,0.54070,...,0.59799,0.43636,0.63322,0.76684,0.40639,0.53525,0.43527,0.56586,0.61025,1.0

In [34]:
percent = (train.shape[0]/(train.shape[0]+tour.shape[0]))*100
print('TOTAL DATA')
print('% of total data, training:') #total = training + tournament
print(percent)
print('% of total data, tournament:')
print(100-percent)

TOTAL DATA
% of total data, training:
60.563748100716296
% of total data, tournament:
39.436251899283704